### ISSUE TITLE
Use helm-docs syntax on comments

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/wharf-helm#10]
https://github.com/norwoodj/helm-docs uses a particular syntax for its comments. Like this:

```yaml
controller:
  # -- Configure the healthcheck for the ingress controller
  livenessProbe:
    httpGet:
      # -- This is the liveness check endpoint
      path: /healthz
      port: http
```

The double dash `--` is very important. We need to add this to group the settings appropriately, as since #8 they are a bit jumbled.
